// sprint/check.mjs: the design-studio loop's own check (generated by center/loopkit.mjs).
// Command, agents, board, handoff, inbox, keeper, crew, knobs and vision: PASS/WARN/FAIL
// lines, exit 1 on FAIL. A FAIL is the lead's first packet (the keeper carries it).
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const NAME = "design-studio";
const MARKER = "Run the design-studio loop from `sprint/board.md` toward `VISION.md`";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CENTER_VISION = "C:/Users/me/Desktop/center/vision-check.mjs";
const out = [];
const say = (level, what) => out.push([level, what]);
const read = (rel) => { try { return readFileSync(join(ROOT, rel), "utf8").replace(/\r\n/g, "\n"); } catch { return null; } };
const front = (text) => {
  const m = String(text ?? "").match(/^---\n([\s\S]*?)\n---\n/);
  return m ? { raw: m[1], ...Object.fromEntries(m[1].split("\n").map((l) => l.match(/^([\w-]+):\s*(.*)$/)).filter(Boolean).map((x) => [x[1], x[2].trim()])) } : null;
};
const table = (md) => {
  const lines = String(md ?? "").split("\n").filter((l) => l.trim().startsWith("|"));
  const cells = (l) => l.trim().replace(/^\||\|$/g, "").split("|").map((c) => c.trim());
  if (lines.length < 2) return [];
  const head = cells(lines[0]);
  return lines.slice(2).map((l) => Object.fromEntries(head.map((h, i) => [h, cells(l)[i] ?? ""])));
};

// 1. The command and the features the keeper and the lead need.
const cmd = read(".opencode/commands/sprint.md");
if (!cmd) say("FAIL", "command missing: .opencode/commands/sprint.md");
else {
  for (const [what, need] of [["keeper marker", MARKER], ["handoff path", "sprint/handoff.md"], ["stop line", "LOOP STOP:"],
    ["foreground batches", "packet: <name>"], ["re-read after compaction", "compaction"], ["the chain", "The chain"],
    ["one-off card", "Goal, Scope, Proof and Stop"], ["recurring duties", "## Recurring duties"], ["halt file", "sprint/halt"]]) {
    say(cmd.includes(need) ? "PASS" : "FAIL", `command ${cmd.includes(need) ? "has" : "lost"}: ${what}`);
  }
  if (front(cmd)?.agent !== "lead") say("FAIL", "command: front matter `agent: lead` missing");
}

// 2. Agents: only the lead is primary; helpers cannot fan out or ask; the judge is read-only.
const agentsDir = join(ROOT, ".opencode", "agents");
const roles = existsSync(agentsDir) ? readdirSync(agentsDir).filter((f) => f.endsWith(".md")).map((f) => f.slice(0, -3)) : [];
for (const role of ["lead", "builder", "judge", "planner", "researcher", "pilot", "runner", "overseer"]) {
  const fm = front(read(`.opencode/agents/${role}.md`));
  if (!fm) { say("FAIL", `agent ${role}: file or front matter missing`); continue; }
  const want = role === "lead" ? "primary" : "subagent";
  if (fm.mode !== want) say("FAIL", `agent ${role}: mode ${fm.mode}, want ${want}`);
  if (!fm.model) say("FAIL", `agent ${role}: no model`);
  // Maxim 2026-10-04: every agent may send helpers (the keeper caps a helper at 10, subagent_depth 2 stops deeper).
  if (!/^\s+task:\s*allow\b/m.test(fm.raw)) say("FAIL", `agent ${role}: needs task: allow (every agent may send helpers)`);
  if (!/^\s+question:\s*deny\b/m.test(fm.raw)) say("FAIL", `agent ${role}: question: deny missing (nobody answers at night)`);
  if (["judge", "overseer"].includes(role) && !/^\s+edit:\s*deny\b/m.test(fm.raw)) say("FAIL", `agent ${role}: must be read-only (edit: deny)`);
}
if (!out.some(([l, w]) => l === "FAIL" && w.startsWith("agent"))) say("PASS", `agents: ${roles.length} roles, only the lead primary`);
const cfg = read("opencode.jsonc") ?? read("opencode.json");
if (!cfg || !/"default_agent"\s*:\s*"lead"/.test(cfg)) say("FAIL", "opencode config: default_agent lead missing");

// 3. The board, the handoff, the inbox.
const board = table(read("sprint/board.md"));
if (!board.length) say("FAIL", "board: sprint/board.md or its table missing");
else {
  const ids = board.map((r) => r.ID);
  const dup = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dup.length) say("FAIL", `board: IDs twice: ${dup.join(", ")}`);
  const bad = board.filter((r) => !["TOP", "READY", "DOING", "BLOCKED", "OWNER", "DONE"].includes(r.Status));
  if (bad.length) say("FAIL", `board: bad status on ${bad.map((r) => r.ID).join(", ")}`);
  const noSha = board.filter((r) => r.Status === "DONE" && !/\b[0-9a-f]{7,40}\b/.test(r.Evidence ?? ""));
  if (noSha.length) say("FAIL", `board: DONE without a commit SHA: ${noSha.map((r) => r.ID).join(", ")}`);
  const open = board.filter((r) => ["TOP", "READY", "DOING"].includes(r.Status)).length;
  say(open ? "PASS" : "WARN", `board: ${board.length} rows, ${open} open`);
}
const handoff = read("sprint/handoff.md");
if (!handoff) say("FAIL", "handoff missing: sprint/handoff.md");
else if (!new RegExp(`^# ${NAME} handoff - round \\d+ \\(token [^)]+\\)`).test(handoff)) say("FAIL", `handoff: first line must be "# ${NAME} handoff - round N (token <4 hex>)"`);
if (!/^## Open\b/m.test(read("sprint/inbox.md") ?? "")) say("FAIL", "inbox: sprint/inbox.md needs an ## Open section");

// 4. The keeper knows this loop.
const keeper = read(".opencode/plugin/loop-keeper.js");
if (!keeper) say("FAIL", "keeper missing: .opencode/plugin/loop-keeper.js");
else {
  if (!keeper.includes(`repo: "${NAME}"`)) say("FAIL", `keeper: CFG repo is not "${NAME}"`);
  if (!keeper.includes(JSON.stringify(MARKER))) say("FAIL", "keeper: CFG marker differs from the command's");
  const known = keeper.includes(`${JSON.stringify(NAME)}: {`) || keeper.includes(`  ${NAME}: {`);
  say(known ? "PASS" : "FAIL", known ? `keeper: ${NAME} is in its REPOS table` : `keeper: ${NAME} is missing from its REPOS table (node loopkit.mjs register, then sync-keeper)`);
}

// 5. The crew: every seat parses and names an agent this repo has.
const standing = join(ROOT, "sprint", "queue", "standing");
const seats = existsSync(standing) ? readdirSync(standing).filter((f) => f.endsWith(".md")) : [];
for (const f of seats) {
  const fm = front(read(`sprint/queue/standing/${f}`));
  if (!fm?.role || !fm?.title) say("FAIL", `seat ${f}: no front matter with role: and title:`);
  else if (!roles.includes(fm.role)) say("FAIL", `seat ${f}: role ${fm.role} has no agent`);
}
say(seats.length >= 5 ? "PASS" : "FAIL", `crew: ${seats.length} standing seats`);
if (seats.some((f) => /chain:\s*start/.test(read(`sprint/queue/standing/${f}`) ?? "")) && !read("sprint/queue/chain/review.md")) say("FAIL", "crew: a chain: start seat but no chain/review.md");

// 6. Knobs: foreground batches.
let knobs = null;
try { knobs = JSON.parse(read(".opencode/knobs.json") ?? "null"); } catch { knobs = null; }
if (!knobs?.knobs?.width?.value) say("FAIL", "knobs: .opencode/knobs.json has no width");
else if (String(knobs.knobs.dispatch?.value ?? "foreground") !== "foreground") say("WARN", "knobs: dispatch is not foreground (the owner wants every helper seen live)");
else say("PASS", `knobs: width ${knobs.knobs.width.value}, foreground batches`);

// 7. The vision: center's checkVision on this repo's VISION.md (scorecard, parts, gaps, steal map).
// The research tables may sit in VISION-TABLES.md next to VISION.md (center's readVision joins them the same way).
const visionTop = read("VISION.md");
const vision = visionTop == null ? null : `${visionTop}${read("VISION-TABLES.md") == null ? "" : `\n\n${read("VISION-TABLES.md")}`}`;
if (vision == null) say("FAIL", "VISION.md missing");
else {
  let checkVision = null;
  try { if (existsSync(CENTER_VISION)) ({ checkVision } = await import(pathToFileURL(CENTER_VISION).href)); } catch { checkVision = null; }
  if (checkVision) for (const f of checkVision(vision)) say(f.level, `vision: ${f.what}`);
  else for (const s of ["Scorecard", "Parts vs the best", "Open gaps", "Steal map"]) if (!new RegExp(`^## .*${s}`, "m").test(vision)) say("FAIL", `vision: no "${s}" section`);
}

// 8. Privacy guard: no real CV content, no PII, when repo may be public.
const forbidList = new Map();
try { const f = JSON.parse(read(".opencode/forbid.json") ?? "{}"); forbidList.set("forbid", f.forbid ?? []); } catch {}

const privacyFiles = new Map();
let privacyFail = false;
const gitFiles = (cmd) => {
  try {
    const { execSync } = require("node:child_process");
    return String(execSync(`git ls-files`, { cwd: ROOT, encoding: "utf8" })).split("\n").filter(f => f.trim());
  } catch { return []; }
};
for (const file of gitFiles()) {
  if (file.includes("/") && (file.endsWith(".md") || file.endsWith(".mjs") || file.endsWith(".js") || file.endsWith(".json") || file.endsWith(".html"))) {
    const content = read(file);
    if (!content) continue;
    // Check for gmail addresses
    if (/\bgmail\.com\b/i.test(content)) {
      privacyFiles.set(file, privacyFiles.get(file) ?? []);
      privacyFiles.get(file).push("gmail.com address");
      privacyFail = true;
    }
    // Check for Israeli mobile (05X XXXXXXX), excluding placeholders (all same digit, 123, 555 patterns)
    const mobMatch = content.match(/\b05\d{7}\b/g);
    if (mobMatch) {
      for (const mob of mobMatch) {
        const digits = mob.slice(2);
        const allSame = /^(.)\1{6}$/.test(digits);
        const isPattern = /^(123|555)/.test(digits);
        if (!allSame && !isPattern) {
          privacyFiles.set(file, privacyFiles.get(file) ?? []);
          privacyFiles.get(file).push(`Israeli mobile ${mob}`);
          privacyFail = true;
        }
      }
    }
    // Check for konovalov or diklaaltman outside forbid list
    for (const word of ["konovalov", "diklaaltman"]) {
      const forbid = forbidList.get("forbid") ?? [];
      const lines = content.split("\n");
      for (let i = 0; i < lines.length; i++) {
        if (new RegExp(`\\b${word}\\b`, "i").test(lines[i])) {
          if (!forbid.some(f => lines[i].includes(f))) {
            privacyFiles.set(file, privacyFiles.get(file) ?? []);
            privacyFiles.get(file).push(`${word} at line ${i + 1}`);
            privacyFail = true;
          }
        }
      }
    }
  }
}
if (privacyFail) {
  for (const [file, issues] of privacyFiles) {
    say("FAIL", `privacy: ${file} contains ${issues.join(", ")}`);
  }
} else {
  say("PASS", "privacy: no PII or real CV content found");
}

for (const [l, w] of out) console.log(`[${l}] ${w}`);
const n = (l) => out.filter(([x]) => x === l).length;
const worst = n("FAIL") ? "FAIL" : n("WARN") ? "WARN" : "PASS";
console.log(`RESULT ${worst}: ${n("PASS")} pass, ${n("WARN")} warn, ${n("FAIL")} fail`);
if (worst === "FAIL") process.exitCode = 1;
