// tools/fonts.mjs: self-hosted OFL-1.1 fonts (fontsource, MIT packager).
// Every design carries its own fonts so the customer renders the same pixels
// and a CV PDF holds real Hebrew text (no system-font roulette).
//
// Commands:
//   node tools/fonts.mjs add <family...> [--weights 400,700] [--subsets hebrew,latin]
//   node tools/fonts.mjs list
//   node tools/fonts.mjs pair he        (Hebrew pair for the career maker)
//   node tools/fonts.mjs pair display   (two bold Latin display families, OFL-1.1 verified)
//   node tools/fonts.mjs --check        (FONTS PASS proof line)
//
// add copies the used woff2 files from node_modules/@fontsource/<family>/files/
// into fonts/<family>/, writes fonts/fonts.css (relative @font-face,
// font-display: swap) and the family's OFL.txt (copy of the package LICENSE).
// Only woff2, only the requested weights/subsets: fonts/ stays far under 3 MB.
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const FONTS_DIR = join(ROOT, "fonts");
export const MANIFEST_FILE = join(FONTS_DIR, "fonts.json");
export const CSS_FILE = join(FONTS_DIR, "fonts.css");
export const MAX_BYTES = 3 * 1024 * 1024;

export const DEFAULT_WEIGHTS = [400, 700];
export const DEFAULT_SUBSETS = ["latin"];

// Hebrew pair for the career maker (O-007): Heebo body + Frank Ruhl Libre headings.
export const HEBREW_PAIR = {
  body: { slug: "heebo", family: "Heebo", weights: [400, 700], subsets: ["hebrew", "latin"] },
  headings: { slug: "frank-ruhl-libre", family: "Frank Ruhl Libre", weights: [400, 700], subsets: ["hebrew", "latin"] },
};

// Two bold Latin display families for covers (O-002). Licenses verified with
// `npm view <pkg> license` on 2026-10-04, both OFL-1.1; fontsource packager MIT.
export const DISPLAY_PAIR = [
  { slug: "rubik", family: "Rubik", weights: [700], subsets: ["latin"], license: "OFL-1.1" },
  { slug: "inter", family: "Inter", weights: [700], subsets: ["latin"], license: "OFL-1.1" },
];

export function normalizeSlug(raw) {
  return String(raw ?? "").trim().toLowerCase().replace(/\s+/g, "-");
}

export function parseList(raw, fallback) {
  if (raw == null) return [...fallback];
  return String(raw)
    .split(",")
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
}

export function parseAddArgs(args) {
  const families = [];
  let weights = null;
  let subsets = null;
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--weights" && args[i + 1] != null) {
      weights = parseList(args[++i], DEFAULT_WEIGHTS).map(Number).filter((n) => Number.isInteger(n));
    } else if (a.startsWith("--weights=")) {
      weights = parseList(a.slice("--weights=".length), DEFAULT_WEIGHTS).map(Number).filter((n) => Number.isInteger(n));
    } else if (a === "--subsets" && args[i + 1] != null) {
      subsets = parseList(args[++i], DEFAULT_SUBSETS);
    } else if (a.startsWith("--subsets=")) {
      subsets = parseList(a.slice("--subsets=".length), DEFAULT_SUBSETS);
    } else if (!a.startsWith("-")) {
      families.push(normalizeSlug(a));
    }
  }
  return { families, weights: weights ?? [...DEFAULT_WEIGHTS], subsets: subsets ?? [...DEFAULT_SUBSETS] };
}

export function packageDir(slug) {
  return join(ROOT, "node_modules", "@fontsource", slug);
}

export function familyDisplayName(slug) {
  try {
    const meta = JSON.parse(readFileSync(join(packageDir(slug), "metadata.json"), "utf8"));
    if (typeof meta.family === "string" && meta.family.trim()) return meta.family.trim();
  } catch { /* fallback below */ }
  return slug.split("-").map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w)).join(" ");
}

export function readManifest() {
  try {
    const raw = JSON.parse(readFileSync(MANIFEST_FILE, "utf8"));
    if (raw && typeof raw === "object" && raw.families && typeof raw.families === "object") return raw;
  } catch { /* fresh manifest */ }
  return { families: {} };
}

export function writeManifest(manifest) {
  mkdirSync(FONTS_DIR, { recursive: true });
  writeFileSync(MANIFEST_FILE, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

// One @font-face block per copied file. Weight parsed from the file name
// (<slug>-<subset>-<weight>-normal.woff2); src is relative to fonts/fonts.css.
export function cssFor(manifest) {
  const lines = [
    "/* Generated by tools/fonts.mjs from node_modules/@fontsource (OFL-1.1). Edit via `fonts.mjs add`, not by hand. */",
  ];
  const slugs = Object.keys(manifest?.families ?? {}).sort();
  for (const slug of slugs) {
    const entry = manifest.families[slug];
    const family = entry.cssFamily ?? familyDisplayName(slug);
    for (const file of [...(entry.files ?? [])].sort()) {
      const m = file.match(/-(\d+)-normal\.woff2$/);
      const weight = m ? m[1] : "400";
      lines.push(`@font-face { font-family: "${family}"; font-style: normal; font-display: swap; font-weight: ${weight}; src: url(./${slug}/${file}) format("woff2"); }`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function writeCss(manifest) {
  mkdirSync(FONTS_DIR, { recursive: true });
  writeFileSync(CSS_FILE, cssFor(manifest), "utf8");
}

export function totalBytes(manifest) {
  let total = 0;
  for (const [slug, entry] of Object.entries(manifest?.families ?? {})) {
    for (const file of entry.files ?? []) {
      try {
        total += statSync(join(FONTS_DIR, slug, file)).size;
      } catch { /* counted as missing by --check */ }
    }
  }
  return total;
}

export function addFamilies(families, { weights = DEFAULT_WEIGHTS, subsets = DEFAULT_SUBSETS } = {}) {
  const manifest = readManifest();
  const added = [];
  const warnings = [];
  for (const slug of families.map(normalizeSlug).filter(Boolean)) {
    const pkg = packageDir(slug);
    if (!existsSync(join(pkg, "package.json"))) {
      throw new Error(`@fontsource/${slug} not installed — next: npm i @fontsource/${slug}`);
    }
    const filesDir = join(pkg, "files");
    const cssFamily = familyDisplayName(slug);
    mkdirSync(join(FONTS_DIR, slug), { recursive: true });
    const files = [];
    for (const subset of subsets) {
      for (const weight of weights) {
        const base = `${slug}-${subset}-${weight}-normal.woff2`;
        const src = join(filesDir, base);
        if (!existsSync(src)) {
          warnings.push(`${slug}: no ${subset}/${weight} woff2 in @fontsource/${slug} (skipped)`);
          continue;
        }
        copyFileSync(src, join(FONTS_DIR, slug, base));
        files.push(base);
      }
    }
    if (files.length === 0) {
      throw new Error(`${slug}: none of ${subsets.join("+")}/${weights.join("+")} exist in @fontsource/${slug} — next: check metadata.json subsets/weights`);
    }
    // License receipt: the package LICENSE is the OFL-1.1 text.
    const licSrc = join(pkg, "LICENSE");
    if (existsSync(licSrc)) {
      copyFileSync(licSrc, join(FONTS_DIR, slug, "OFL.txt"));
    } else {
      writeFileSync(join(FONTS_DIR, slug, "OFL.txt"), `SIL Open Font License 1.1 for ${cssFamily} (via @fontsource/${slug}).\n`, "utf8");
      warnings.push(`${slug}: package LICENSE missing, wrote OFL.txt placeholder`);
    }
    manifest.families[slug] = {
      pkg: `@fontsource/${slug}`,
      cssFamily,
      weights: [...weights],
      subsets: [...subsets],
      files: [...new Set(files)].sort(),
      license: "OFL-1.1",
    };
    added.push(slug);
  }
  writeManifest(manifest);
  writeCss(manifest);
  return { manifest, added, warnings };
}

export function listFonts() {
  const manifest = readManifest();
  const slugs = Object.keys(manifest.families ?? {}).sort();
  if (slugs.length === 0) return { manifest, lines: ["no families yet — next: node tools/fonts.mjs add heebo --subsets hebrew,latin"] };
  const lines = slugs.map((slug) => {
    const e = manifest.families[slug];
    return `${slug} (${e.cssFamily}): weights ${e.weights.join(",")} subsets ${e.subsets.join(",")} files ${e.files.length} license ${e.license ?? "OFL-1.1"}`;
  });
  lines.push(`total ${(totalBytes(manifest) / 1024).toFixed(1)}KB in fonts/ (cap ${MAX_BYTES / 1024 / 1024}MB)`);
  return { manifest, lines };
}

export function pairText(which) {
  if (which === "he") {
    const { body, headings } = HEBREW_PAIR;
    return [
      `Hebrew pair: body ${body.family} (@fontsource/${body.slug} ${body.weights.join(",")} ${body.subsets.join(",")}) + headings ${headings.family} (@fontsource/${headings.slug} ${headings.weights.join(",")} ${headings.subsets.join(",")})`,
      `usage: font-family: "${headings.family}", "${body.family}", "Noto Sans Hebrew", Arial, sans-serif`,
    ].join("\n");
  }
  if (which === "display") {
    return DISPLAY_PAIR.map(
      (d) => `Display: ${d.family} (@fontsource/${d.slug} ${d.weights.join(",")} ${d.subsets.join(",")} bold, license ${d.license} via npm view 2026-10-04)`,
    ).join("\n");
  }
  throw new Error(`unknown pair ${JSON.stringify(which)} — next: pair he | pair display`);
}

export function checkFonts() {
  const results = [];
  const ok = (name, pass, detail) => results.push({ name, pass, detail });
  const manifest = readManifest();
  const slugs = Object.keys(manifest.families ?? {});
  ok("fonts.json lists 1+ families", slugs.length >= 1, slugs.length ? slugs.sort().join(", ") : "empty — next: node tools/fonts.mjs add heebo --subsets hebrew,latin");
  let allExist = true;
  for (const slug of slugs) {
    for (const file of manifest.families[slug].files ?? []) {
      if (!existsSync(join(FONTS_DIR, slug, file))) {
        allExist = false;
        ok(`file exists ${slug}/${file}`, false, "missing — next: re-run fonts.mjs add");
      }
    }
  }
  if (allExist && slugs.length) ok("every listed file exists", true, `${slugs.length} families on disk`);
  const heebo = manifest.families.heebo;
  const hebrewFile = heebo?.files?.find((f) => f.includes("-hebrew-"));
  ok(
    "Hebrew subset file present for heebo",
    Boolean(heebo && hebrewFile && existsSync(join(FONTS_DIR, "heebo", hebrewFile))),
    heebo ? (hebrewFile ?? "no -hebrew- file listed") : "heebo not added yet",
  );
  let oftOk = true;
  for (const slug of slugs) {
    if (!existsSync(join(FONTS_DIR, slug, "OFL.txt"))) {
      oftOk = false;
      ok(`OFL.txt present ${slug}`, false, "missing — next: re-run fonts.mjs add");
    }
  }
  if (oftOk && slugs.length) ok("OFL.txt present per family", true, `${slugs.length} receipts`);
  if (!existsSync(CSS_FILE)) {
    ok("fonts.css parses", false, "fonts/fonts.css missing — next: re-run fonts.mjs add");
  } else {
    const css = readFileSync(CSS_FILE, "utf8");
    const faces = css.match(/@font-face\s*\{[^}]*\}/g) ?? [];
    const swaps = faces.filter((b) => /font-display\s*:\s*swap/.test(b) && /url\(\.\//.test(b));
    ok("fonts.css parses (@font-face + swap + relative url)", swaps.length >= 1 && swaps.length === faces.length, `${swaps.length}/${faces.length} blocks relative + swap`);
  }
  const bytes = totalBytes(manifest);
  ok("fonts/ under 3MB woff2 only", bytes <= MAX_BYTES, `${(bytes / 1024).toFixed(1)}KB`);
  return { pass: results.every((r) => r.pass), results, manifest };
}

const isMain = (() => {
  try {
    return fileURLToPath(import.meta.url) === resolve(process.argv[1]);
  } catch {
    return false;
  }
})();

if (isMain) {
  const args = process.argv.slice(2);
  try {
    if (args.includes("--check")) {
      const { pass, results } = checkFonts();
      for (const r of results) console.log(`[${r.pass ? "PASS" : "FAIL"}] ${r.name}: ${r.detail}`);
      console.log(pass ? `FONTS PASS: ${results.length} gates green, customer renders the same pixels` : `FONTS FAIL: ${results.filter((r) => !r.pass).length} failing check(s)`);
      if (!pass) process.exitCode = 1;
    } else if (args[0] === "add") {
      const { families, weights, subsets } = parseAddArgs(args.slice(1));
      if (families.length === 0) {
        console.log("usage: node tools/fonts.mjs add <family...> [--weights 400,700] [--subsets hebrew,latin]");
        process.exitCode = 2;
      } else {
        const { added, warnings } = addFamilies(families, { weights, subsets });
        for (const w of warnings) console.log(`[WARN] ${w}`);
        console.log(`FONTS ADD: ${added.join(", ")} weights ${weights.join(",")} subsets ${subsets.join(",")}`);
      }
    } else if (args[0] === "list") {
      const { lines } = listFonts();
      for (const l of lines) console.log(l);
    } else if (args[0] === "pair") {
      console.log(pairText(args[1]));
    } else {
      console.log("usage: node tools/fonts.mjs add <family...> [--weights 400,700] [--subsets hebrew,latin] | list | pair he | pair display | --check");
      process.exitCode = 2;
    }
  } catch (e) {
    console.log(`FONTS FAIL: ${String(e.message || e)}`);
    process.exitCode = 1;
  }
}
