// tools/tokens.mjs (DS-02 tokens-01): tokens.json -> tokens.css + docs page.
// Single source of truth: samples/cover/tokens.json. The page may use only
// var(--*) colors; this module fails closed on hardcoded colors outside
// tokens.css and on the 5 Brand-kit checks (vars, pairs, type, spacing, diff).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { contrastRatio } from "./audit.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_JSON = join(ROOT, "samples", "cover", "tokens.json");
const DEFAULT_CSS = join(ROOT, "samples", "cover", "tokens.css");
const DEFAULT_DOCS = join(ROOT, "samples", "cover", "tokens.html");
const DEFAULT_PAGE = join(ROOT, "samples", "cover", "page.html");

const HEX = /^#[0-9a-fA-F]{6}$/;

export function readTokens(jsonPath = DEFAULT_JSON) {
  const raw = JSON.parse(readFileSync(jsonPath, "utf8"));
  return raw;
}

export function buildCss(tokens) {
  const lines = [
    "/* Generated by tools/tokens.mjs from tokens.json (DS-02). Edit the JSON, not this file. */",
    ":root {",
  ];
  for (const [k, v] of Object.entries(tokens.colors ?? {})) lines.push(`  --${k}: ${String(v).toLowerCase()};`);
  if (tokens.fonts?.display) lines.push(`  --font-display: ${tokens.fonts.display};`);
  if (tokens.fonts?.body) lines.push(`  --font-body: ${tokens.fonts.body};`);
  for (const [k, v] of Object.entries(tokens.spacing ?? {})) lines.push(`  --space-${k}: ${v};`);
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

export function buildDocs(tokens) {
  const swatches = Object.entries(tokens.colors ?? {})
    .map(
      ([k, v]) =>
        `    <div class="sw"><span class="chip" style="background: var(--${k})"></span><code>--${k}: ${String(v).toLowerCase()}</code></div>`,
    )
    .join("\n");
  return `<!DOCTYPE html>
<!-- Generated by tools/tokens.mjs (DS-02). Docs page: every color via var(--*), no hex in this file. -->
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<title>Tokens docs</title>
<link rel="stylesheet" href="tokens.css">
<style>
  body { background: var(--paper); color: var(--ink); font-family: var(--font-body); margin: 0; padding: var(--space-lg); }
  h1 { font-family: var(--font-display); }
  .grid { display: grid; gap: var(--space-sm); margin: var(--space-md) 0; }
  .sw { display: flex; align-items: center; gap: var(--space-sm); border: 1px solid var(--line); padding: var(--space-sm); }
  .chip { width: 48px; height: 48px; border: 1px solid var(--line); display: inline-block; }
  .cta { display: inline-block; background: var(--accent); color: var(--on-accent); padding: var(--space-sm) var(--space-md); }
  .muted { color: var(--muted); }
</style>
</head>
<body>
  <h1>Brand tokens</h1>
  <p class="muted">Source: tokens.json. Type: display plus body. Spacing scale below.</p>
  <div class="grid">
${swatches}
  </div>
  <p style="font-family: var(--font-display)">Display type specimen: DESIGN THAT SHIPS</p>
  <p>Body type specimen: Brief to rendered, audited pixels.</p>
  <p><span class="cta">Accent CTA specimen</span></p>
</body>
</html>
`;
}

function hardColors(text, stripCode = false) {
  // Docs pages list hex values inside <code> labels; those are labels, not
  // styling. Strip <code> blocks before scanning when asked.
  let hay = String(text ?? "");
  if (stripCode) hay = hay.replace(/<code>[\s\S]*?<\/code>/gi, "<code></code>");
  return hay.match(/#[0-9a-fA-F]{6}\b/g) ?? [];
}

export function checkTokens({ json = DEFAULT_JSON, css = DEFAULT_CSS, docs = DEFAULT_DOCS, page = DEFAULT_PAGE } = {}) {
  const results = [];
  const ok = (name, pass, detail) => results.push({ name, pass, detail });

  if (!existsSync(json)) {
    ok("tokens.json exists", false, json);
    return { pass: false, results };
  }
  ok("tokens.json exists", true, json);
  let tokens;
  try {
    tokens = JSON.parse(readFileSync(json, "utf8"));
  } catch (e) {
    ok("tokens.json parses", false, String(e.message || e));
    return { pass: false, results };
  }
  ok("tokens.json parses", true, "valid JSON");

  // vars: 5+ colors, all #rrggbb.
  const colors = tokens.colors ?? {};
  const names = Object.keys(colors);
  const allHex = names.every((k) => HEX.test(String(colors[k] ?? "")));
  ok("vars: 5+ colors are #rrggbb", names.length >= 5 && allHex, `${names.length} colors${allHex ? "" : " (non-hex found)"}`);

  // pairs: the three shipped text pairs hit 4.5:1.
  const pairs = [
    ["ink", "paper"],
    ["muted", "paper"],
    ["on-accent", "accent"],
  ];
  for (const [fg, bg] of pairs) {
    try {
      const ratio = contrastRatio(String(colors[fg]).toLowerCase(), String(colors[bg]).toLowerCase());
      ok(`pairs: ${fg} on ${bg} >= 4.5:1`, ratio >= 4.5, `${ratio.toFixed(2)}:1`);
    } catch (e) {
      ok(`pairs: ${fg} on ${bg} >= 4.5:1`, false, String(e.message || e));
    }
  }

  // type: display + body stacks present.
  const typeOk = Boolean(tokens.fonts?.display) && Boolean(tokens.fonts?.body);
  ok("type: display + body stacks", typeOk, typeOk ? "both stacks present" : "fonts.display/body required");

  // spacing: 3+ --space-* tokens shaped Npx.
  const spacing = tokens.spacing ?? {};
  const sNames = Object.keys(spacing);
  const shapeOk = sNames.every((k) => /^\d+px$/.test(String(spacing[k] ?? "")));
  ok("spacing: 3+ --space-* tokens", sNames.length >= 3 && shapeOk, `${sNames.length} tokens${shapeOk ? "" : " (shape must be Npx)"}`);

  // diff: tokens.css on disk equals the generator output.
  const expected = buildCss(tokens);
  if (!existsSync(css)) {
    ok("diff: tokens.css matches tokens.json", false, "tokens.css missing (run --build)");
  } else {
    const onDisk = readFileSync(css, "utf8");
    ok(
      "diff: tokens.css matches tokens.json",
      onDisk.replace(/\r\n/g, "\n") === expected.replace(/\r\n/g, "\n"),
      onDisk.replace(/\r\n/g, "\n") === expected.replace(/\r\n/g, "\n") ? "in sync" : "drift: run node tools/tokens.mjs --build",
    );
  }

  // no hardcoded colors in the consumer page + docs page.
  // Docs <code> labels may name hex values; styling must still use var(--*).
  for (const [label, file, strip] of [
    ["page.html", page, false],
    ["tokens.html", docs, true],
  ]) {
    if (!existsSync(file)) {
      ok(`no hardcoded colors in ${label}`, false, `${label} missing`);
    } else {
      const hard = hardColors(readFileSync(file, "utf8"), strip);
      ok(`no hardcoded colors in ${label}`, hard.length === 0, hard.length ? `hardcoded ${hard.slice(0, 3).join(", ")}` : "all color via var(--*)");
    }
  }

  // docs page exists and links tokens.css.
  if (existsSync(docs)) {
    const html = readFileSync(docs, "utf8");
    ok("docs: tokens.html lists the kit", html.includes("tokens.css") && html.includes("--accent"), "tokens.css linked, swatches listed");
  } else {
    ok("docs: tokens.html lists the kit", false, "tokens.html missing (run --build)");
  }

  return { pass: results.every((r) => r.pass), results };
}

export function buildAll({ json = DEFAULT_JSON, css = DEFAULT_CSS, docs = DEFAULT_DOCS } = {}) {
  const tokens = readTokens(json);
  writeFileSync(css, buildCss(tokens), "utf8");
  writeFileSync(docs, buildDocs(tokens), "utf8");
  return { css, docs };
}

const isMain = (() => {
  try {
    return fileURLToPath(import.meta.url) === resolve(process.argv[1]);
  } catch {
    return false;
  }
})();

if (isMain) {
  const args = process.argv.slice(2);
  if (args.includes("--build")) {
    const i = args.indexOf("--build");
    const j = args[i + 1]?.startsWith("--") || args[i + 1] == null ? {} : { json: resolve(args[i + 1]) };
    const out = buildAll(j.json ? { json: j.json } : {});
    console.log(`TOKENS BUILD ${out.css} + ${out.docs}`);
  }
  if (args.includes("--check") || args.length === 0) {
    const { pass, results } = checkTokens();
    for (const r of results) console.log(`[${r.pass ? "PASS" : "FAIL"}] ${r.name}: ${r.detail}`);
    console.log(pass ? "TOKENS PASS: tokens.json -> tokens.css + docs, 0 hardcoded colors" : `TOKENS FAIL: ${results.filter((r) => !r.pass).length} failing check(s)`);
    if (!pass) process.exitCode = 1;
  }
  if (!args.includes("--build") && !args.includes("--check") && args.length > 0) {
    console.log("usage: node tools/tokens.mjs [--build [tokens.json]] [--check]");
    process.exitCode = 2;
  }
}
